name: Prepare release
on:
  push:
    branches:
    - 'release/**'
jobs:
  job_compute_release_name:
    runs-on: ubuntu-18.04
    container:
      image: docker://alpine/git:v2.24.3
    outputs:
      release_name: ${{ steps.step_compute_release_name.outputs.release_name }}
    steps:
      - id: step_compute_release_name
        env:
          GIT_REF: ${{ github.ref }}
        run: |
          release_name=${GIT_REF#refs/heads/release/}
          echo "Release name=$release_name"
          echo "::set-output name=release_name::$release_name"

  job_build_test_and_generate_desc:
    needs: job_compute_release_name
    runs-on: ubuntu-18.04
    container:
      image: docker://docker:stable-git
      options: --name=runner
    strategy:
      matrix:
        android_api: [28, 29]
        android_ndk: ["--android-ndk", ""]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build test deploy describe image
        env:
          RELEASE_NAME: ${{ needs.job_compute_release_name.outputs.release_name }}
        run: ./ci_cd.sh --build --test --desc --android-api ${{ matrix.android_api }} ${{ matrix.android_ndk }}

      - name: Upload image description
        uses: actions/upload-artifact@v2-preview
        with:
          path: desc/output/*.md
          name: images_description

  job_create_pr:
    needs: [job_compute_release_name, job_build_test_and_generate_desc]
    runs-on: ubuntu-18.04
    container:
      image: docker://alpine/git:v2.24.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate changelog file
        uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.GITHUB_TOKEN }} --future-release ${{ needs.job_compute_release_name.outputs.release_name }}

      - name: Fetch images description
        uses: actions/download-artifact@v2-preview
        with:
          name: images_description
          path: images_description

      - name: Commit changes
        uses: actions-x/commit@v1
        with:
          message: Add changelog and images description

      - name: Create pr
        id: step_create_pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "master"
